apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: e1fdr1h9k-java-quarkus 
  janus-idp.io/tekton: e1fdr1h9k-java-quarkus
  backstage.io/kubernetes-id: e1fdr1h9k-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e1fdr1h9k-java-quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  